FROM rocker/r-ver:4.0.2

RUN apt-get update -qq && apt-get install -y \
      libssl-dev \
      libcurl4-gnutls-dev

MAINTAINER Gabriel K Alves, https://github.com/gabrielkoyama

RUN R -e "install.packages('plumber', dependencies=TRUE)"
RUN R -e "install.packages('yaml', dependencies=TRUE)"
RUN R -e "install.packages('swagger', dependencies=TRUE)"

# RUN R -e "install.packages('devtools')"
# RUN R -e "devtools::install_github('SofanitAraya/CropPhenology')"
# RUN R -e "install.packages('rgdal')"
# RUN R -e "install.packages('signal')"
# RUN R -e "install.packages('imputeTS')"

COPY / /

EXPOSE 8080

ENTRYPOINT ["Rscript", "app.R"]